Context Manager: with flushing(MainEngine()) as eng:
ProjectQ-Framework/ProjectQ pull request #449
Opened 2022-10-20 09:32 UTC by cclauss

Simplify the creation, use, and flushing of any Engine using a Python context manager.

When exiting the `with` block, the engine is _automatically_ flushed.

Modeled after https://docs.python.org/3/library/contextlib.html#contextlib.closing
```python
from projectq import MainEngine, flushing  # import the main compiler engine
from projectq.ops import (
    H,
    Measure,
)  # import the operations we want to perform (Hadamard and measurement)

with flushing(MainEngine()) as eng:  # create a default compiler (the back-end is a simulator)
    qubit = eng.allocate_qubit()  # allocate a quantum register with 1 qubit

    H | qubit  # apply a Hadamard gate
    Measure | qubit  # measure the qubit

    # This line is no longer required... eng.flush()

print(f"Measured {int(qubit)}")  # converting a qubit to int or bool gives access to the measurement result

2022-10-22 08:03 UTC, Takishima requested changes
All in all, a good addition. I just have one major comment that I would like to see addressed.

2022-10-22 08:03 UTC, Takishima commented on projectq/cengines/__init__.py
> +def flushing(thing):
Missing docstring for this function.

Also, I would name the argument `engine` in order to make clear to users that a compiler engine is expected.

Lastly, please add at least one simple unit test that makes sure that this does indeed calls `flush()`. You could for example create a dummy engine class that derives from `DummyEngine` and override its `flush` method to track whether it was called.

2022-10-22 08:03 UTC, Takishima commented on CHANGELOG.md
> +## [vNext] - 2022-mm-dd
Please replace this line with this one (that's actually a mistake from my side when releasing the latest version):

`## [Unreleased]`

2022-10-22 08:04 UTC, Takishima commented
Also, if you have not done so already, please send an email to info@projectq.ch to request the ProjectQ license agreement that you'll have to sign before we can merge this PR.

2022-10-22 15:50 UTC, cclauss commented
% `pytest`
```
...
projectq/cengines/_withflushing_test.py ..                               [ 58%]
...
```

2022-10-24 07:21 UTC, Takishima approved these changes

2022-10-24 07:22 UTC, Takishima commented
Looks good to me. Now before I can merge this, I do need to have you sign the ProjectQ CLA, so please send an email to info@projectq.ch in order to request the form that you can sign electronically.

2022-10-27 08:01 UTC, merged

2022-10-27 08:33 UTC, Takishima commented
Thanks for the contribution!